/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Hospital.Administrator;

import Business.EcoSystem;
import Business.Enterprise.HospitalEnterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author user
 */
public class HospitalAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HospitalAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    HospitalEnterprise enterprise;
    public HospitalAdminWorkAreaJPanel(JPanel userProcessContainer,EcoSystem ecosystem, HospitalEnterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
        this.enterprise = enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEmpManage = new javax.swing.JButton();
        btnOrgManage = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnUserManage = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 102, 102));

        btnEmpManage.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEmpManage.setText("Manage Employee");
        btnEmpManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpManageActionPerformed(evt);
            }
        });

        btnOrgManage.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnOrgManage.setText("Manage Organization");
        btnOrgManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrgManageActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Hospital Administrator Work Panel");

        btnUserManage.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnUserManage.setText("Manage User");
        btnUserManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserManageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnUserManage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEmpManage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOrgManage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)))
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnOrgManage)
                .addGap(18, 18, 18)
                .addComponent(btnEmpManage)
                .addGap(18, 18, 18)
                .addComponent(btnUserManage)
                .addGap(63, 63, 63))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpManageActionPerformed
        ManageHospitalEmployeeJPanel manageHospitalEmployeeJPanel=new ManageHospitalEmployeeJPanel(userProcessContainer, ecosystem, enterprise);
        userProcessContainer.add("manageHospitalEmployeeJPanel",manageHospitalEmployeeJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnEmpManageActionPerformed

    private void btnOrgManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrgManageActionPerformed
        ManageHospitalOrganizationJPanel manageHospitalOrganizationJPanel=new ManageHospitalOrganizationJPanel(userProcessContainer, ecosystem,enterprise);
        userProcessContainer.add("manageHospitalOrganizationJPanel",manageHospitalOrganizationJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnOrgManageActionPerformed

    private void btnUserManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserManageActionPerformed
        ManageHospitalUserJPanel manageHospitalUserJPanel=new ManageHospitalUserJPanel(userProcessContainer, enterprise,ecosystem);
        userProcessContainer.add("manageHospitalUserJPanel",manageHospitalUserJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnUserManageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEmpManage;
    private javax.swing.JButton btnOrgManage;
    private javax.swing.JButton btnUserManage;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
