/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Welfare.BLO;

import Business.Enterprise.EducationEnterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Enterprise.WelfareEnterprise;
import Business.Network.Network;
import Business.Organization.EducationOrganization;
import Business.Organization.EducationSupervisorOrganization;
import Business.Organization.WelfareOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SupervisorWorkRequest;
import Business.WorkQueue.WelfareSLOWorkRequest;
import javax.swing.JPanel;

/**
 *
 * @author user
 */
public class ProcessBLOWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessBLOWorkRequestJPanel
     */
    JPanel userProcessContainer;
    WelfareSLOWorkRequest request;
    WelfareOrganization organization;
    UserAccount userAccount;
    WelfareEnterprise enterprise;
    Network network;
    public ProcessBLOWorkRequestJPanel(JPanel userProcessContainer, WelfareOrganization organization,UserAccount userAccount, WelfareEnterprise enterprise, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.organization = organization;
        this.userAccount = userAccount;
        this.enterprise=enterprise;
        this.network = network;
        PopulateTypeCombo();
    }
    private void PopulateTypeCombo(){
        ddlAssign.removeAllItems();
        for(EducationEnterprise ed : network.getEnterpriseDirectory().getEducationnterpriseList()){
            ddlAssign.addItem(ed);
        }
        for(HospitalEnterprise ed : network.getEnterpriseDirectory().getHospitalnterpriseList()){
            ddlAssign.addItem(ed);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ddlAssign = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        btnAssign = new javax.swing.JButton();

        jLabel1.setText("Assign To");

        ddlAssign.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ddlAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddlAssignActionPerformed(evt);
            }
        });

        jLabel2.setText("Message");

        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAssign)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMessage)
                            .addComponent(ddlAssign, 0, 120, Short.MAX_VALUE))))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ddlAssign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAssign)
                .addContainerGap(116, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        boolean flag = true;
        SupervisorWorkRequest supRequest = new SupervisorWorkRequest();
        String message = txtMessage.getText();
        supRequest.setMessage(message);
        supRequest.setSender(userAccount);
        supRequest.setStatus("Sent");
        
        EducationOrganization org = null;
        
        
        for(EducationEnterprise edent : network.getEnterpriseDirectory().getEducationnterpriseList()){
            if(flag){
                for (EducationOrganization organization : edent.getEducationOrganizationDirectory().getEducationOrganizationList()){
                    if (organization instanceof EducationSupervisorOrganization){
                        org = organization;
                        break;
                    }
                    
                }
            }
        
            if (org!=null){
                if(org.getWorkQueue().getWorkRequestList().size()<=5){
                    org.getWorkQueue().getWorkRequestList().add(supRequest);
                    userAccount.getWorkQueue().getWorkRequestList().add(supRequest);
                    break;
                }
                else{
                    flag = false;
                }
            }
        }
    }//GEN-LAST:event_btnAssignActionPerformed

    private void ddlAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddlAssignActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddlAssignActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JComboBox ddlAssign;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtMessage;
    // End of variables declaration//GEN-END:variables
}
